In [2]:
from __future__ import print_function
import torch

# Tensors

Construct a 5x3 matrix, uninitialized

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 6.4460e-43, 0.0000e+00],
        [0.0000e+00, 1.4776e+20, 0.0000e+00]])


Construct a randomly initialized matrix

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.2839, 0.9148, 0.2324],
        [0.7022, 0.1399, 0.2930],
        [0.7812, 0.7401, 0.9532],
        [0.8108, 0.7691, 0.8944],
        [0.1266, 0.8469, 0.9828]])


Construct a matrix filled zeros and of dtype long

In [5]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data

In [6]:
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype)
x = torch.tensor([5, 3])
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32
tensor([5, 3])
torch.int64


create a tensor based on an existing tensor

In [7]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[ 1.1046,  0.5188, -0.8375],
        [-0.4812, -0.7695,  0.9350],
        [-1.1870, -0.4566,  0.8873],
        [-0.4317, -0.8150,  0.4956],
        [ 0.8434,  0.5296, -2.0848]])


In [9]:
print(x.size())

torch.Size([5, 3])


# Operations

Addition

In [12]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print('x\n',x)
print('y\n',y)
print('x + y\n',x + y)

x
 tensor([[0.9814, 0.3186, 0.5997],
        [0.6463, 0.9362, 0.4847],
        [0.5116, 0.8579, 0.7853],
        [0.0266, 0.1954, 0.2446],
        [0.2443, 0.1996, 0.5790]])
y
 tensor([[0.1360, 0.0895, 0.2758],
        [0.2099, 0.1716, 0.6579],
        [0.1850, 0.5512, 0.8615],
        [0.3799, 0.0383, 0.4390],
        [0.6426, 0.6546, 0.7110]])
x + y
 tensor([[1.1174, 0.4081, 0.8755],
        [0.8563, 1.1078, 1.1426],
        [0.6966, 1.4091, 1.6468],
        [0.4065, 0.2337, 0.6836],
        [0.8870, 0.8542, 1.2900]])


In [13]:
print(torch.add(x, y))

tensor([[1.1174, 0.4081, 0.8755],
        [0.8563, 1.1078, 1.1426],
        [0.6966, 1.4091, 1.6468],
        [0.4065, 0.2337, 0.6836],
        [0.8870, 0.8542, 1.2900]])


Addition: providing an output tensor as argument

In [14]:
result = torch.empty(5,3)       ## create empty matrix
torch.add(x, y, out = result)   ## argument
print(result)

tensor([[1.1174, 0.4081, 0.8755],
        [0.8563, 1.1078, 1.1426],
        [0.6966, 1.4091, 1.6468],
        [0.4065, 0.2337, 0.6836],
        [0.8870, 0.8542, 1.2900]])


Addition: in-place

In [15]:
y.add_(x) ## y = y + x
print(y)
## Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

tensor([[1.1174, 0.4081, 0.8755],
        [0.8563, 1.1078, 1.1426],
        [0.6966, 1.4091, 1.6468],
        [0.4065, 0.2337, 0.6836],
        [0.8870, 0.8542, 1.2900]])


In [16]:
print(x[:, 1]) ## 2th col

tensor([0.3186, 0.9362, 0.8579, 0.1954, 0.1996])


Resizing: If you want to resize/reshape tensor, you can use torch.view

In [17]:
x = torch.randn(4,4)
print(x.size())
print(x)
y = x.view(16)
print(y.size())
print(y)
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print(z.size())
print(z)

torch.Size([4, 4])
tensor([[ 0.3308,  0.6803,  0.2890, -1.0978],
        [-1.1738,  2.0580,  1.6572, -0.2439],
        [ 1.2794, -0.0717,  0.4712,  0.3036],
        [ 0.1187, -0.6628,  0.5527,  0.2228]])
torch.Size([16])
tensor([ 0.3308,  0.6803,  0.2890, -1.0978, -1.1738,  2.0580,  1.6572, -0.2439,
         1.2794, -0.0717,  0.4712,  0.3036,  0.1187, -0.6628,  0.5527,  0.2228])
torch.Size([2, 8])
tensor([[ 0.3308,  0.6803,  0.2890, -1.0978, -1.1738,  2.0580,  1.6572, -0.2439],
        [ 1.2794, -0.0717,  0.4712,  0.3036,  0.1187, -0.6628,  0.5527,  0.2228]])


If you have a one element tensor, use .item() to get the value as a Python number

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.0685])
2.0685229301452637


# NumPy Bridge

In [19]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b) ##

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting NumPy Array to Torch Tensor

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [22]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([3.0685], device='cuda:0')
tensor([3.0685], dtype=torch.float64)
