Central to all neural networks in PyTorch is the autograd package. Let’s first briefly visit this, and we will then go to training our first neural network.

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

# Tensor

In [1]:
import torch

To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.

In [2]:
x = torch.ones(2,2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 3
print(z)
out = z.mean()
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


In [5]:
a = torch.randn(2,2)
a = (a * 3)/(a - 1)
print(a, a.requires_grad)
a.requires_grad_(True)
b = (a * a).sum()
print(b, b.requires_grad)

tensor([[  0.0504,   1.5019],
        [-25.4347,   0.6954]]) False
tensor(649.6643, grad_fn=<SumBackward0>) True


# Gradients

In [6]:
out.backward() ## Because out contains a single scalar, == out.backward(torch.tensor(1.))
print(x.grad) ## Print gradients d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


torch.autograd is an engine for computing Jacobian-vector product. 

y is no longer a scalar. torch.autograd could not compute the full Jacobian directly, but if we just want the Jacobian-vector product, simply pass the vector to backward as argument

In [7]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([1533.1184, -798.2988, -593.1037], grad_fn=<MulBackward0>)


In [8]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


You can also stop autograd from tracking history on Tensors with .requires_grad=True by wrapping the code block in with torch.no_grad()

In [9]:
print(x.requires_grad)
print((x ** 2).requires_grad)
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
